### ISSUE TITLE
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

### ISSUE THREAD

**Issue by partofthething** [Keeyees/0001#1]
I've tried 3 of my new KeeYees boards with three different cables and I keep getting this error when flashing the blink example as described in the manual. 

```
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]: Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]:   File "/home/nick/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/upload.py", line 66, in <module>
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]:     esptool.main(cmdline)
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]:   File "/home/nick/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 3552, in main
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]:     esp.connect(args.before, args.connect_attempts)
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]:   File "/home/nick/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 529, in connect
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]:     raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]: esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
Oct  2 14:40:29 orion arduino-arduinoide.desktop[308672]: esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
```

I'm using Arduino 1.8.15 and ESP8266 board manager v. 3.0.2. 

Uploading to other related boards (e.g. NodeMCU) works fine on my machine.

**Comment by partofthething** [comment]
Ok so this is probably a linux driver issue. I was on ubuntu 21.04 with that issue and when I switched to another system (pop OS) it worked fine. I'll try to figure out the driver issue.
